// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/azmanabdlh/ayo-example/internal/league-management/dtos"
	"github.com/azmanabdlh/ayo-example/internal/league-management/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddRecordGoal provides a mock function for the type MockService
func (_mock *MockService) AddRecordGoal(ctx context.Context, matchID int64, goalParam dtos.GoalParam) error {
	ret := _mock.Called(ctx, matchID, goalParam)

	if len(ret) == 0 {
		panic("no return value specified for AddRecordGoal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, dtos.GoalParam) error); ok {
		r0 = returnFunc(ctx, matchID, goalParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddRecordGoal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRecordGoal'
type MockService_AddRecordGoal_Call struct {
	*mock.Call
}

// AddRecordGoal is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID int64
//   - goalParam dtos.GoalParam
func (_e *MockService_Expecter) AddRecordGoal(ctx any, matchID any, goalParam any) *MockService_AddRecordGoal_Call {
	return &MockService_AddRecordGoal_Call{Call: _e.mock.On("AddRecordGoal", ctx, matchID, goalParam)}
}

func (_c *MockService_AddRecordGoal_Call) Run(run func(ctx context.Context, matchID int64, goalParam dtos.GoalParam)) *MockService_AddRecordGoal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 dtos.GoalParam
		if args[2] != nil {
			arg2 = args[2].(dtos.GoalParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AddRecordGoal_Call) Return(err error) *MockService_AddRecordGoal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddRecordGoal_Call) RunAndReturn(run func(ctx context.Context, matchID int64, goalParam dtos.GoalParam) error) *MockService_AddRecordGoal_Call {
	_c.Call.Return(run)
	return _c
}

// AssignMatchPlayerLineup provides a mock function for the type MockService
func (_mock *MockService) AssignMatchPlayerLineup(ctx context.Context, matchID int64, param dtos.MatchPlayerParam) error {
	ret := _mock.Called(ctx, matchID, param)

	if len(ret) == 0 {
		panic("no return value specified for AssignMatchPlayerLineup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, dtos.MatchPlayerParam) error); ok {
		r0 = returnFunc(ctx, matchID, param)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AssignMatchPlayerLineup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignMatchPlayerLineup'
type MockService_AssignMatchPlayerLineup_Call struct {
	*mock.Call
}

// AssignMatchPlayerLineup is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID int64
//   - param dtos.MatchPlayerParam
func (_e *MockService_Expecter) AssignMatchPlayerLineup(ctx any, matchID any, param any) *MockService_AssignMatchPlayerLineup_Call {
	return &MockService_AssignMatchPlayerLineup_Call{Call: _e.mock.On("AssignMatchPlayerLineup", ctx, matchID, param)}
}

func (_c *MockService_AssignMatchPlayerLineup_Call) Run(run func(ctx context.Context, matchID int64, param dtos.MatchPlayerParam)) *MockService_AssignMatchPlayerLineup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 dtos.MatchPlayerParam
		if args[2] != nil {
			arg2 = args[2].(dtos.MatchPlayerParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AssignMatchPlayerLineup_Call) Return(err error) *MockService_AssignMatchPlayerLineup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AssignMatchPlayerLineup_Call) RunAndReturn(run func(ctx context.Context, matchID int64, param dtos.MatchPlayerParam) error) *MockService_AssignMatchPlayerLineup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMatch provides a mock function for the type MockService
func (_mock *MockService) CreateMatch(ctx context.Context, matchParam dtos.MatchParam) error {
	ret := _mock.Called(ctx, matchParam)

	if len(ret) == 0 {
		panic("no return value specified for CreateMatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.MatchParam) error); ok {
		r0 = returnFunc(ctx, matchParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMatch'
type MockService_CreateMatch_Call struct {
	*mock.Call
}

// CreateMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - matchParam dtos.MatchParam
func (_e *MockService_Expecter) CreateMatch(ctx any, matchParam any) *MockService_CreateMatch_Call {
	return &MockService_CreateMatch_Call{Call: _e.mock.On("CreateMatch", ctx, matchParam)}
}

func (_c *MockService_CreateMatch_Call) Run(run func(ctx context.Context, matchParam dtos.MatchParam)) *MockService_CreateMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.MatchParam
		if args[1] != nil {
			arg1 = args[1].(dtos.MatchParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateMatch_Call) Return(err error) *MockService_CreateMatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateMatch_Call) RunAndReturn(run func(ctx context.Context, matchParam dtos.MatchParam) error) *MockService_CreateMatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVenue provides a mock function for the type MockService
func (_mock *MockService) CreateVenue(ctx context.Context, venueParam dtos.VenueParam) error {
	ret := _mock.Called(ctx, venueParam)

	if len(ret) == 0 {
		panic("no return value specified for CreateVenue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.VenueParam) error); ok {
		r0 = returnFunc(ctx, venueParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVenue'
type MockService_CreateVenue_Call struct {
	*mock.Call
}

// CreateVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - venueParam dtos.VenueParam
func (_e *MockService_Expecter) CreateVenue(ctx any, venueParam any) *MockService_CreateVenue_Call {
	return &MockService_CreateVenue_Call{Call: _e.mock.On("CreateVenue", ctx, venueParam)}
}

func (_c *MockService_CreateVenue_Call) Run(run func(ctx context.Context, venueParam dtos.VenueParam)) *MockService_CreateVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.VenueParam
		if args[1] != nil {
			arg1 = args[1].(dtos.VenueParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateVenue_Call) Return(err error) *MockService_CreateVenue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateVenue_Call) RunAndReturn(run func(ctx context.Context, venueParam dtos.VenueParam) error) *MockService_CreateVenue_Call {
	_c.Call.Return(run)
	return _c
}

// FindMatchHighlight provides a mock function for the type MockService
func (_mock *MockService) FindMatchHighlight(ctx context.Context, matchID int64) (model.MatchHighlight, error) {
	ret := _mock.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for FindMatchHighlight")
	}

	var r0 model.MatchHighlight
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (model.MatchHighlight, error)); ok {
		return returnFunc(ctx, matchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) model.MatchHighlight); ok {
		r0 = returnFunc(ctx, matchID)
	} else {
		r0 = ret.Get(0).(model.MatchHighlight)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, matchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FindMatchHighlight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMatchHighlight'
type MockService_FindMatchHighlight_Call struct {
	*mock.Call
}

// FindMatchHighlight is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID int64
func (_e *MockService_Expecter) FindMatchHighlight(ctx any, matchID any) *MockService_FindMatchHighlight_Call {
	return &MockService_FindMatchHighlight_Call{Call: _e.mock.On("FindMatchHighlight", ctx, matchID)}
}

func (_c *MockService_FindMatchHighlight_Call) Run(run func(ctx context.Context, matchID int64)) *MockService_FindMatchHighlight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FindMatchHighlight_Call) Return(matchHighlight model.MatchHighlight, err error) *MockService_FindMatchHighlight_Call {
	_c.Call.Return(matchHighlight, err)
	return _c
}

func (_c *MockService_FindMatchHighlight_Call) RunAndReturn(run func(ctx context.Context, matchID int64) (model.MatchHighlight, error)) *MockService_FindMatchHighlight_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function for the type MockService
func (_mock *MockService) Finish(ctx context.Context, matchID int64) error {
	ret := _mock.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, matchID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockService_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID int64
func (_e *MockService_Expecter) Finish(ctx any, matchID any) *MockService_Finish_Call {
	return &MockService_Finish_Call{Call: _e.mock.On("Finish", ctx, matchID)}
}

func (_c *MockService_Finish_Call) Run(run func(ctx context.Context, matchID int64)) *MockService_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Finish_Call) Return(err error) *MockService_Finish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Finish_Call) RunAndReturn(run func(ctx context.Context, matchID int64) error) *MockService_Finish_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyVenue provides a mock function for the type MockService
func (_mock *MockService) ModifyVenue(ctx context.Context, venueID int64, venueParam dtos.VenueParam) error {
	ret := _mock.Called(ctx, venueID, venueParam)

	if len(ret) == 0 {
		panic("no return value specified for ModifyVenue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, dtos.VenueParam) error); ok {
		r0 = returnFunc(ctx, venueID, venueParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ModifyVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyVenue'
type MockService_ModifyVenue_Call struct {
	*mock.Call
}

// ModifyVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID int64
//   - venueParam dtos.VenueParam
func (_e *MockService_Expecter) ModifyVenue(ctx any, venueID any, venueParam any) *MockService_ModifyVenue_Call {
	return &MockService_ModifyVenue_Call{Call: _e.mock.On("ModifyVenue", ctx, venueID, venueParam)}
}

func (_c *MockService_ModifyVenue_Call) Run(run func(ctx context.Context, venueID int64, venueParam dtos.VenueParam)) *MockService_ModifyVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 dtos.VenueParam
		if args[2] != nil {
			arg2 = args[2].(dtos.VenueParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ModifyVenue_Call) Return(err error) *MockService_ModifyVenue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ModifyVenue_Call) RunAndReturn(run func(ctx context.Context, venueID int64, venueParam dtos.VenueParam) error) *MockService_ModifyVenue_Call {
	_c.Call.Return(run)
	return _c
}

// SubstitutePlayer provides a mock function for the type MockService
func (_mock *MockService) SubstitutePlayer(ctx context.Context, matchID int64, param dtos.SubstitutePlayerParam) error {
	ret := _mock.Called(ctx, matchID, param)

	if len(ret) == 0 {
		panic("no return value specified for SubstitutePlayer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, dtos.SubstitutePlayerParam) error); ok {
		r0 = returnFunc(ctx, matchID, param)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SubstitutePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubstitutePlayer'
type MockService_SubstitutePlayer_Call struct {
	*mock.Call
}

// SubstitutePlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID int64
//   - param dtos.SubstitutePlayerParam
func (_e *MockService_Expecter) SubstitutePlayer(ctx any, matchID any, param any) *MockService_SubstitutePlayer_Call {
	return &MockService_SubstitutePlayer_Call{Call: _e.mock.On("SubstitutePlayer", ctx, matchID, param)}
}

func (_c *MockService_SubstitutePlayer_Call) Run(run func(ctx context.Context, matchID int64, param dtos.SubstitutePlayerParam)) *MockService_SubstitutePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 dtos.SubstitutePlayerParam
		if args[2] != nil {
			arg2 = args[2].(dtos.SubstitutePlayerParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SubstitutePlayer_Call) Return(err error) *MockService_SubstitutePlayer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SubstitutePlayer_Call) RunAndReturn(run func(ctx context.Context, matchID int64, param dtos.SubstitutePlayerParam) error) *MockService_SubstitutePlayer_Call {
	_c.Call.Return(run)
	return _c
}
