// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/azmanabdlh/ayo-example/internal/team-management/dtos"
	"github.com/azmanabdlh/ayo-example/internal/team-management/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AssignPlayerTeam provides a mock function for the type MockService
func (_mock *MockService) AssignPlayerTeam(ctx context.Context, playerID int64, teamID int64) error {
	ret := _mock.Called(ctx, playerID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for AssignPlayerTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, playerID, teamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AssignPlayerTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPlayerTeam'
type MockService_AssignPlayerTeam_Call struct {
	*mock.Call
}

// AssignPlayerTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID int64
//   - teamID int64
func (_e *MockService_Expecter) AssignPlayerTeam(ctx any, playerID any, teamID any) *MockService_AssignPlayerTeam_Call {
	return &MockService_AssignPlayerTeam_Call{Call: _e.mock.On("AssignPlayerTeam", ctx, playerID, teamID)}
}

func (_c *MockService_AssignPlayerTeam_Call) Run(run func(ctx context.Context, playerID int64, teamID int64)) *MockService_AssignPlayerTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AssignPlayerTeam_Call) Return(err error) *MockService_AssignPlayerTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AssignPlayerTeam_Call) RunAndReturn(run func(ctx context.Context, playerID int64, teamID int64) error) *MockService_AssignPlayerTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, param dtos.TeamParam) error {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.TeamParam) error); ok {
		r0 = returnFunc(ctx, param)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - param dtos.TeamParam
func (_e *MockService_Expecter) Create(ctx any, param any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, param)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, param dtos.TeamParam)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.TeamParam
		if args[1] != nil {
			arg1 = args[1].(dtos.TeamParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(err error) *MockService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, param dtos.TeamParam) error) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockService
func (_mock *MockService) Find(ctx context.Context, id int64) (model.Team, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 model.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (model.Team, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) model.Team); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Team)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockService_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) Find(ctx any, id any) *MockService_Find_Call {
	return &MockService_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockService_Find_Call) Run(run func(ctx context.Context, id int64)) *MockService_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Find_Call) Return(team model.Team, err error) *MockService_Find_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockService_Find_Call) RunAndReturn(run func(ctx context.Context, id int64) (model.Team, error)) *MockService_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockService
func (_mock *MockService) FindAll(ctx context.Context, page int, limit int) ([]model.Team, error) {
	ret := _mock.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Team, error)); ok {
		return returnFunc(ctx, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []model.Team); ok {
		r0 = returnFunc(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockService_Expecter) FindAll(ctx any, page any, limit any) *MockService_FindAll_Call {
	return &MockService_FindAll_Call{Call: _e.mock.On("FindAll", ctx, page, limit)}
}

func (_c *MockService_FindAll_Call) Run(run func(ctx context.Context, page int, limit int)) *MockService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_FindAll_Call) Return(teams []model.Team, err error) *MockService_FindAll_Call {
	_c.Call.Return(teams, err)
	return _c
}

func (_c *MockService_FindAll_Call) RunAndReturn(run func(ctx context.Context, page int, limit int) ([]model.Team, error)) *MockService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindPlayer provides a mock function for the type MockService
func (_mock *MockService) FindPlayer(ctx context.Context, playerID int64) (model.Player, error) {
	ret := _mock.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for FindPlayer")
	}

	var r0 model.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (model.Player, error)); ok {
		return returnFunc(ctx, playerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) model.Player); ok {
		r0 = returnFunc(ctx, playerID)
	} else {
		r0 = ret.Get(0).(model.Player)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FindPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPlayer'
type MockService_FindPlayer_Call struct {
	*mock.Call
}

// FindPlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID int64
func (_e *MockService_Expecter) FindPlayer(ctx any, playerID any) *MockService_FindPlayer_Call {
	return &MockService_FindPlayer_Call{Call: _e.mock.On("FindPlayer", ctx, playerID)}
}

func (_c *MockService_FindPlayer_Call) Run(run func(ctx context.Context, playerID int64)) *MockService_FindPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FindPlayer_Call) Return(player model.Player, err error) *MockService_FindPlayer_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *MockService_FindPlayer_Call) RunAndReturn(run func(ctx context.Context, playerID int64) (model.Player, error)) *MockService_FindPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// Modify provides a mock function for the type MockService
func (_mock *MockService) Modify(ctx context.Context, teamID int64, param dtos.TeamParam) error {
	ret := _mock.Called(ctx, teamID, param)

	if len(ret) == 0 {
		panic("no return value specified for Modify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, dtos.TeamParam) error); ok {
		r0 = returnFunc(ctx, teamID, param)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Modify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modify'
type MockService_Modify_Call struct {
	*mock.Call
}

// Modify is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - param dtos.TeamParam
func (_e *MockService_Expecter) Modify(ctx any, teamID any, param any) *MockService_Modify_Call {
	return &MockService_Modify_Call{Call: _e.mock.On("Modify", ctx, teamID, param)}
}

func (_c *MockService_Modify_Call) Run(run func(ctx context.Context, teamID int64, param dtos.TeamParam)) *MockService_Modify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 dtos.TeamParam
		if args[2] != nil {
			arg2 = args[2].(dtos.TeamParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Modify_Call) Return(err error) *MockService_Modify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Modify_Call) RunAndReturn(run func(ctx context.Context, teamID int64, param dtos.TeamParam) error) *MockService_Modify_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockService
func (_mock *MockService) Remove(ctx context.Context, teamID int64) error {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
func (_e *MockService_Expecter) Remove(ctx any, teamID any) *MockService_Remove_Call {
	return &MockService_Remove_Call{Call: _e.mock.On("Remove", ctx, teamID)}
}

func (_c *MockService_Remove_Call) Run(run func(ctx context.Context, teamID int64)) *MockService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Remove_Call) Return(err error) *MockService_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Remove_Call) RunAndReturn(run func(ctx context.Context, teamID int64) error) *MockService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePlayer provides a mock function for the type MockService
func (_mock *MockService) RemovePlayer(ctx context.Context, playerID int64) error {
	ret := _mock.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePlayer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, playerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemovePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePlayer'
type MockService_RemovePlayer_Call struct {
	*mock.Call
}

// RemovePlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID int64
func (_e *MockService_Expecter) RemovePlayer(ctx any, playerID any) *MockService_RemovePlayer_Call {
	return &MockService_RemovePlayer_Call{Call: _e.mock.On("RemovePlayer", ctx, playerID)}
}

func (_c *MockService_RemovePlayer_Call) Run(run func(ctx context.Context, playerID int64)) *MockService_RemovePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RemovePlayer_Call) Return(err error) *MockService_RemovePlayer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemovePlayer_Call) RunAndReturn(run func(ctx context.Context, playerID int64) error) *MockService_RemovePlayer_Call {
	_c.Call.Return(run)
	return _c
}
