// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middleware

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function for the type MockProvider
func (_mock *MockProvider) ValidateToken(ctx context.Context, token string) (int64, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockProvider_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockProvider_Expecter) ValidateToken(ctx any, token any) *MockProvider_ValidateToken_Call {
	return &MockProvider_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *MockProvider_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *MockProvider_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_ValidateToken_Call) Return(n int64, err error) *MockProvider_ValidateToken_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProvider_ValidateToken_Call) RunAndReturn(run func(ctx context.Context, token string) (int64, error)) *MockProvider_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthenticate creates a new instance of MockAuthenticate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticate {
	mock := &MockAuthenticate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticate is an autogenerated mock type for the Authenticate type
type MockAuthenticate struct {
	mock.Mock
}

type MockAuthenticate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticate) EXPECT() *MockAuthenticate_Expecter {
	return &MockAuthenticate_Expecter{mock: &_m.Mock}
}

// IsAccountValid provides a mock function for the type MockAuthenticate
func (_mock *MockAuthenticate) IsAccountValid(ctx context.Context, userID int64) bool {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsAccountValid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAuthenticate_IsAccountValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccountValid'
type MockAuthenticate_IsAccountValid_Call struct {
	*mock.Call
}

// IsAccountValid is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuthenticate_Expecter) IsAccountValid(ctx any, userID any) *MockAuthenticate_IsAccountValid_Call {
	return &MockAuthenticate_IsAccountValid_Call{Call: _e.mock.On("IsAccountValid", ctx, userID)}
}

func (_c *MockAuthenticate_IsAccountValid_Call) Run(run func(ctx context.Context, userID int64)) *MockAuthenticate_IsAccountValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticate_IsAccountValid_Call) Return(b bool) *MockAuthenticate_IsAccountValid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAuthenticate_IsAccountValid_Call) RunAndReturn(run func(ctx context.Context, userID int64) bool) *MockAuthenticate_IsAccountValid_Call {
	_c.Call.Return(run)
	return _c
}
